server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: springcloud-service
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
redis:
  host: localhost
  #服务器地址
  port: 6379
  #服务器端口
#  database: 1
# Redis数据库索引（默认为0） 密码之类的 默认是没有的可以写